// Code generated by goagen v1.2.0-dirty, DO NOT EDIT.
//
// API "CSAPI": swagger TestHelpers
//
// Command:
// $ goagen
// --design=github.com/negronjl/csapi/design
// --out=$(GOPATH)/src/github.com/negronjl/csapi
// --version=v1.2.0-dirty

package test
